DELIMITER $$
CREATE PROCEDURE update_buser(IN pid_buser INT, IN PDATE DATE, IN pPWPREVIOUS VARCHAR(100), IN pPWCURRENT VARCHAR(100), IN pid_USER INT)
	BEGIN
		UPDATE buser
        SET
		  DATE = pDATE,
		  PWPREVIOUS = pPWPREVIOUS, 
		  PWCURRENT = pPWCURRENT,  
		  ID_USER = pid_USER
        WHERE ID_BUSER = pid_buser;
    END$$
    
DELIMITER ;