 DELIMITER $$
CREATE PROCEDURE update_JOB(IN pID_JOB INT, IN pBIRTHDATE date, IN pDESCRIPTION VARCHAR(70), IN pPUBDATE DATE, IN pDUEDATE DATE, IN pVANCACIE int, IN pid_STATE INT, IN pid_CAREER INT, IN pid_ADEGREE INT, IN pid_JOBPOS INT)
	BEGIN
		UPDATE job 
        SET
		  BIRTHDATE = PBIRTHDATE,
		  DESCRIPTION = PDESCRIPTION, 
		  PUBDATE = PPUBDATE,
		  DUEDATE = PDUEDATES,
		  VACANCIES = PVACANTES,
		  pid_state = ID_STATE,
		  ID_CAREER = pId_CAREER,
		  ID_ADEGREE = PID_ADEGREE,
		  ID_JOBPOS = PID_JOBPOS
		  Where pid_job = id_job;
	END$$
    
DELIMITER ;