#DISTRITOS SANJOSE
call insert_distrito('San Ignacio',1,1);
call insert_distrito('Guaitil',1,1);
call insert_distrito('Palmichal',1,1);
call insert_distrito('Cangrejal',1,1);
call insert_distrito('Sabanillas',1,1);
call insert_distrito('Alajuelita',1,2);
call insert_distrito('San Josecito',1,2);
call insert_distrito('San Antonio',1,2);
call insert_distrito('Concepción',1,2);
call insert_distrito('San Felipe',1,2);
call insert_distrito('Aserrí',1,3);
call insert_distrito('Tarbaca',1,3);
call insert_distrito('Vuelta de Jorco',1,3);
call insert_distrito('San Gabriel',1,3);
call insert_distrito('Legua',1,3);
call insert_distrito('Monterrey',1,3);
call insert_distrito('Salitrillos',1,3);
call insert_distrito('Curridabat',1,4);
call insert_distrito('Granadilla',1,4);
call insert_distrito('Sánchez',1,4);
call insert_distrito('Tirrases',1,4);
call insert_distrito('Desamparados',1,5);
call insert_distrito('San Miguel',1,5);
call insert_distrito('San Juan de Dios',1,5);
call insert_distrito('San Rafael Arriba',1,5);
call insert_distrito('San Antonio',1,5);
call insert_distrito('Frailes',1,5);
call insert_distrito('Patarrá',1,5);
call insert_distrito('San Cristóbal',1,5);
call insert_distrito('Rosario',1,5);
call insert_distrito('Damas',1,5);
call insert_distrito('San Rafael Abajo',1,5);
call insert_distrito('Gravilias',1,5);
call insert_distrito('Los Guido',1,5);
call insert_distrito('Santa María',1,6);
call insert_distrito('Jardín',1,6);
call insert_distrito('Copey',1,6);
call insert_distrito('Escazú',1,7);
call insert_distrito('San Antonio',1,7);
call insert_distrito('San Rafael',1,7);
call insert_distrito('Guadalupe',1,8);
call insert_distrito('San Francisco',1,8);
call insert_distrito('Calle Blancos',1,8);
call insert_distrito('Mata de Plátano',1,8);
call insert_distrito('Ipís',1,8);
call insert_distrito('Rancho Redondo',1,8);
call insert_distrito('Purral',1,8);
call insert_distrito('San Pablo',1,9);
call insert_distrito('San Andrés',1,9);
call insert_distrito('Llano Bonito',1,9);
call insert_distrito('San Isidro',1,9);
call insert_distrito('Santa Cruz',1,9);
call insert_distrito('San Antonio',1,9);
call insert_distrito('San Pedro',1,10 );
call insert_distrito('Sabanilla',1,10 );
call insert_distrito('Mercedes',1,10 );
call insert_distrito('San Rafael',1,10 );
call insert_distrito('Ciudad Colón',1,11 );
call insert_distrito('Guayabo',1,11 );
call insert_distrito('Tabarcia',1,11 );
call insert_distrito('Piedras Negras',1,11 );
call insert_distrito('Picagres',1,11 );
call insert_distrito('Jaris',1,11 );
call insert_distrito('Quitirrisí',1,11 );
call insert_distrito('San Vicente',1,12 );
call insert_distrito('San Jerónimo',1,12 );
call insert_distrito('Trinidad',1,12 );
call insert_distrito('San Isidro de El General',1,13 );
call insert_distrito('El General',1,13 );
call insert_distrito('Daniel Flores',1,13 );
call insert_distrito('Rivas',1,13 );
call insert_distrito('San Pedro',1,13 );
call insert_distrito('Platanares',1,13 );
call insert_distrito('Pejibaye',1,13 );
call insert_distrito('Cajón',1,13 );
call insert_distrito('Barú',1,13 );
call insert_distrito('Río Nuevo',1,13 );
call insert_distrito('Páramo',1,13 );
call insert_distrito('La Amistad',1,13 );
call insert_distrito('Santiago',1,14 );
call insert_distrito('Mercedes Sur',1,14 );
call insert_distrito('Barbacoas',1,14 );
call insert_distrito('Grifo Alto',1,14 );
call insert_distrito('San Rafael',1,14 );
call insert_distrito('Candelarita',1,14 );
call insert_distrito('Desamparaditos',1,14 );
call insert_distrito('San Antonio',1,14 );
call insert_distrito('Chires',1,14 );
call insert_distrito('La Cangreja',1,14 );
call insert_distrito('Carmen',1,15 );
call insert_distrito('Merced',1,15 );
call insert_distrito('Hospital',1,15 );
call insert_distrito('Catedral',1,15 );
call insert_distrito('Zapote',1,15 );
call insert_distrito('San Francisco de Dos Ríos',1,15 );
call insert_distrito('Uruca',1,15 );
call insert_distrito('Mata Redonda',1,15 );
call insert_distrito('Pavas',1,15 );
call insert_distrito('Hatillo',1,15 );
call insert_distrito('San Sebastián',1,15 );
call insert_distrito('Santa Ana',1,16 );
call insert_distrito('Salitral',1,16 );
call insert_distrito('Pozos',1,16 );
call insert_distrito('Uruca',1,16 );
call insert_distrito('Piedades',1,16 );
call insert_distrito('Brasil',1,16 );
call insert_distrito('San Marcos',1,17 );
call insert_distrito('San Lorenzo',1,17 );
call insert_distrito('San Carlos',1,17 );
call insert_distrito('San Juan',1,18 );
call insert_distrito('Cinco Esquinas',1,18 );
call insert_distrito('Anselmo Llorente',1,18 );
call insert_distrito('León XIII',1,18 );
call insert_distrito('Colima',1,18 );
call insert_distrito('San Pablo',1,19 );
call insert_distrito('San Pedro',1,19 );
call insert_distrito('San Juan de Mata',1,19 );
call insert_distrito('San Luis',1,19 );
call insert_distrito('Carara',1,19 );
call insert_distrito('San Isidro',1,20 );
call insert_distrito('San Rafael',1,20 );
call insert_distrito('Dulce Nombre de Jesús',1,20 );
call insert_distrito('Patalillo',1,20 );
call insert_distrito('Cascajal',1,20 );