/*
Fecha: 27 OCTUBRE 2018
Autor: Nakisha Dixon
Descripcion: PAQUETE (BODY) PARA BORRAR LAS TABLAS CATALOGOS
*/

/*STATE*/
DELIMITER $$
CREATE PROCEDURE DELETE_STATE(IN pidSTATE INT)
BEGIN
    delete from STATE where id_STATE = pidSTATE;
end
$$
DELIMITER ;

/*COUNTRY*/
DELIMITER $$
CREATE PROCEDURE DELETE_COUNTRY(IN pidPais INT)
BEGIN
    delete from COUNTRY where id_COUNTRY = pidPais;
end
$$
DELIMITER ;

/*PROVINCE*/
DELIMITER $$
CREATE PROCEDURE DELETE_PROVINCE(IN pidPROVINCE INT)
BEGIN
    delete from PROVINCE where id_PROVINCE = pidPROVINCE;
end
$$
DELIMITER ;

/*CANTON*/
DELIMITER $$
CREATE PROCEDURE DELETE_CANTON(IN pidCANTON INT)
BEGIN
    delete from CANTON where id_CANTON = pidCANTON;
end
$$
DELIMITER ;

/*DISTRITO*/
DELIMITER $$
CREATE PROCEDURE DELETE_DISTRITO(IN pidDISTRITO INT)
BEGIN
    delete from DISTRITO where id_DISTRITO = pidDISTRITO;
end
$$
DELIMITER ;

/*TYPE_PERSON*/
DELIMITER $$
CREATE PROCEDURE DELETE_TYPEPERSON(IN pidTYPEPERSON INT)
BEGIN
    delete from TYPE_PERSON where id_TYPEPERSON = pidTYPEPERSON;
end
$$
DELIMITER ;

/*REQUIRIMENT*/
DELIMITER $$
CREATE PROCEDURE DELETE_REQUIRIMENT(IN pidREQUIRIMENT INT)
BEGIN
    delete from REQUIRIMENT where id_REQUIRIMENT = pidREQUIRIMENT;
end
$$
DELIMITER ;

/*NACIONALITY*/
DELIMITER $$
CREATE PROCEDURE DELETE_NACIONALITY(IN pidNACIONALITY INT)
BEGIN
    delete from NACIONALITY where id_NACIONALITY = pidNACIONALITY;
end
$$
DELIMITER ;

/*INDUSTRY*/
DELIMITER $$
CREATE PROCEDURE DELETE_INDUSTRY(IN pidINDUSTRY INT)
BEGIN
    delete from INDUSTRY where id_INDUSTRY = pidINDUSTRY;
end
$$
DELIMITER ;

/*JOB_POSITION*/
DELIMITER $$
CREATE PROCEDURE DELETE_JOB_POSITION(IN pidJOB_POSITION INT)
BEGIN
    delete from JOB_POSITION where id_JOB_POSITION = pidJOB_POSITION;
end
$$
DELIMITER ;

/*CAREER*/
DELIMITER $$
CREATE PROCEDURE DELETE_CAREER(IN pidCAREER INT)
BEGIN
    delete from CAREER where id_CAREER = pidCAREER;
end
$$
DELIMITER ;

/*BENEFITS*/
DELIMITER $$
CREATE PROCEDURE DELETE_BENEFITS(IN pidBENEFITS INT)
BEGIN
    delete from BENEFITS where ID_BENEFITS = pidBENEFITS;
end
$$
DELIMITER ;

/*ACADEMIC_DEGREE*/
DELIMITER $$
CREATE PROCEDURE DELETE_ACADEMIC_DEGREE(IN pidPROVINCE INT)
BEGIN
    delete from ACADEMIC_DEGREE where id_ACADEMIC_DEGREE = pidACADEMIC_DEGREE;
end
$$
DELIMITER ;