
CREATE TABLE `chaodesempleo`.`INDUSTRY` (
  `ID_INDUSTRY` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `NAME` VARCHAR(70) NULL COMMENT 'ATTRIBUTE WITH THE NAME OF THE INDUSTRY OR BUSINESS',
  `INDUSTRY` VARCHAR(15) NULL COMMENT 'STATE OF THE INDUSTRY',
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_INDUSTRY`))
COMMENT = 'CATALOGUE OF INDUSTRY OR BUSINESS';