CREATE TABLE `academic_degree` (
  `ID_ACADEMIC_DEGREE` int(11) NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `NAME` varchar(70) DEFAULT NULL COMMENT 'ATTRIBUTE WITH THE NAME OF THE ACADEMIC DEGREE',
  `ACADEMIC_DEGREE` varchar(15) DEFAULT NULL COMMENT 'STATE OF THE ACADEMIC DEGREE',
  `STATE` int(11) DEFAULT NULL,
  `DATE_CREATION` date DEFAULT NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` varchar(20) DEFAULT NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` date DEFAULT NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` varchar(20) DEFAULT NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_ACADEMIC_DEGREE`),
  KEY `STATE` (`STATE`),
  CONSTRAINT `academic_degree_ibfk_1` FOREIGN KEY (`STATE`) REFERENCES `state` (`id_state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CATALOGUE OF ACADEMIC_DEGREE';
