CREATE TABLE `chaodesempleo`.`DISTRITO` (
  `ID_DISTRITO` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `NAME` VARCHAR(70) NULL COMMENT 'ATTRIBUTE WITH THE NAME OF THE DISTRITO',
  `STATE` VARCHAR(15) NULL COMMENT 'STATE OF THE DISTRITO',
  `ID_CANTON` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE CANTON',
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_DISTRITO`),
  KEY `fk_IDCANTON` (`ID_CANTON`),
  CONSTRAINT `fk_IDCANTON` FOREIGN KEY (`ID_CANTON`) REFERENCES `CANTON` (`ID_CANTON`))
COMMENT = 'CATALOGUE OF DISTRITO';

