CREATE TABLE `chaodesempleo`.`CANTON` (
  `ID_CANTON` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `NAME` VARCHAR(70) NULL COMMENT 'ATTRIBUTE WITH THE NAME OF THE CANTON',
  `STATE` VARCHAR(15) NULL COMMENT 'STATE OF THE CANTON',
  `ID_PROVINCE` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE PROVINCE',
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_CANTON`),
  KEY `fk_IDPROVINCE` (`ID_PROVINCE`),
  CONSTRAINT `fk_IDPROVINCE` FOREIGN KEY (`ID_PROVINCE`) REFERENCES `PROVINCE` (`ID_PROVINCE`))
COMMENT = 'CATALOGUE OF CANTON';

