
CREATE TABLE `chaodesempleo`.`JOB_POSITION` (
  `ID_JOB_POSITION` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `NAME` VARCHAR(70) NULL COMMENT 'ATTRIBUTE WITH THE NAME OF THE JOB_POSITION',
  `STATE` VARCHAR(15) NULL COMMENT 'STATE OF THE JOB_POSITION',
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_JOB_POSITION`))
COMMENT = 'CATALOGUE OF JOB_POSITION';

