CREATE TABLE `chaodesempleo`.`JOBXPERSON` (
  `ID_JOBXPERSON` INT NOT NULL AUTO_INCREMENT COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `PDFCV` VARCHAR(150) COMMENT 'ATTRIBUTE OF PDF CV OF PERSON',  
  `ID_PERSON` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE PERSON',
  `ID_JOB` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE JOB',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_JOBXPERSON`),
  
  KEY `fk_JPIDPERSON` (`ID_PERSON`),
  KEY `fk_IDJOB` (`ID_JOB`),
  CONSTRAINT `fk_JPIDPERSON` FOREIGN KEY (`ID_PERSON`) REFERENCES `PERSON` (`ID_PERSON`),
  CONSTRAINT `fk_IDJOB` FOREIGN KEY (`ID_JOB`) REFERENCES `JOB` (`ID_JOB`))
  
COMMENT = 'TABLE JOB X PERSON';

