CREATE TABLE `chaodesempleo`.`JOB` (
  `ID_JOB` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `BIRTHDATE` DATE COMMENT 'ATTRIBUTE OF BIRTH DATE',
  `DESCRIPTION` VARCHAR(100) COMMENT 'ATTRIBUTE OF DESCRIPTION OF JOB',
  `PUBDATE` DATE COMMENT 'ATTRIBUTE OF PUBLICATION DATE',
  `DUEDATE` DATE COMMENT 'ATTRIBUTE OF DUE DATE OF JOB',
  `VACANCIES` INT COMMENT 'ATTRIBUTE OF VACANCIES OF JOB',
  
  
  `ID_STATE` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE STATE',
  `ID_CAREER` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE CAREER',
  `ID_ADEGREE` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE ACADEMIC DEGREE',
  `ID_JOBPOS` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE JOB POSITION',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_JOB`),
  
  KEY `fk_JIDSTATE` (`ID_STATE`),
  KEY `fk_IDCAREER` (`ID_CAREER`),
  KEY `fk_IDADEGREE` (`ID_ADEGREE`),
  KEY `fk_IDJOBPOS` (`ID_JOBPOS`),
  
  CONSTRAINT `fk_JIDSTATE` FOREIGN KEY (`ID_STATE`) REFERENCES `STATE` (`ID_STATE`),
  CONSTRAINT `fk_IDCAREER` FOREIGN KEY (`ID_CAREER`) REFERENCES `CAREER` (`ID_CAREER`),
  CONSTRAINT `fk_IDADEGREE` FOREIGN KEY (`ID_ADEGREE`) REFERENCES `ACADEMIC_DEGREE` (`ID_ACADEMIC_DEGREE`),
  CONSTRAINT `fk_IDJOBPOS` FOREIGN KEY (`ID_JOBPOS`) REFERENCES `JOB_POSITION` (`ID_JOB_POSITION`))
  
COMMENT = 'TABLE JOBS';

