CREATE TABLE `chaodesempleo`.`EMAIL` (
  `ID_EMAIL` INT NOT NULL auto_increment COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `EMAIL` VARCHAR(70) COMMENT 'ATTRIBUTE OF EMAIL OF PERSON',  
  `ID_PERSON` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE PERSON',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_EMAIL`),
  
  KEY `fk_EMIDPERSON` (`ID_PERSON`),
  CONSTRAINT `fk_EMIDPERSON` FOREIGN KEY (`ID_PERSON`) REFERENCES `PERSON` (`ID_PERSON`))
  
COMMENT = 'TABLE EMAIL OF PERSON';

