CREATE TABLE `chaodesempleo`.`JOBXBENF` (
  `ID_JOBXBENF` INT NOT NULL AUTO_INCREMENT COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',  
  `ID_BENF` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE BENEFIT',
  `ID_JOB` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE JOB',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_JOBXBENF`),
  
  KEY `fk_IDBENF` (`ID_BENF`),
  KEY `fk_JBIDJOB` (`ID_JOB`),
  CONSTRAINT `fk_IDBENF` FOREIGN KEY (`ID_BENF`) REFERENCES `benefits` (`ID_BENEFITS`),
  CONSTRAINT `fk_JBIDJOB` FOREIGN KEY (`ID_JOB`) REFERENCES `JOB` (`ID_JOB`))
  
COMMENT = 'TABLE JOB X BENEFIT';

