CREATE TABLE `chaodesempleo`.`PNUMBER` (
  `ID_PNUMBER` INT NOT NULL COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `PNUMBER` VARCHAR(70) COMMENT 'ATTRIBUTE OF PHONE NUMBER OF PERSON',
  
  `ID_PERSON` INT NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE PERSON',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_PNUMBER`),
  
  KEY `fk_PNIDPERSON` (`ID_PERSON`),
  CONSTRAINT `fk_PNIDPERSON` FOREIGN KEY (`ID_PERSON`) REFERENCES `PERSON` (`ID_PERSON`))
  
COMMENT = 'TABLE PHONE NUMBER OF PERSON';

