CREATE TABLE `chaodesempleo`.`BUSER` (
  `ID_BUSER` INT NOT NULL AUTO_INCREMENT COMMENT 'UNIQUE IDENTIFIER OF THE TABLE',
  `DATE` DATE COMMENT 'ATTRIBUTE OF DATE OF CHANGE OF PASSWORD',
  `PWPREVIOUS` VARCHAR(100) NULL COMMENT 'ATTRIBUTE OF THE PASSWORD PREVIOUS',
  `PWCURRENT` VARCHAR(100) NULL COMMENT 'ATTRIBUTE OF THE PASSWORD CURRENT',  
  `ID_USER` INT not NULL COMMENT 'REFERENCED IDENTIFIER OF THE TABLE USER',
  
  `DATE_CREATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_CREATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  `DATE_LAST_MODIFICATION` DATE NULL COMMENT 'ATTRIBUTE AUDIT',
  `USER_LAST_MODIFICATION` VARCHAR(20) NULL COMMENT 'ATTRIBUTE AUDIT',
  PRIMARY KEY (`ID_BUSER`),
  CONSTRAINT fk_IDUSER FOREIGN KEY (`ID_USER`) REFERENCES `USER`(`ID_USER`)
)
COMMENT = 'TABLE BINNACLE OF USER';

