/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chaodesempleo;

import Utilidades.*;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
/**
 *
 * @author Mariela
 */
public class FormularioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormularioAdmin
     */
    Tabla t = new Tabla();
    
    public FormularioAdmin() {
        initComponents();
        p11.setVisible(false);
        InvisiblesComp();
       
    }
     public void InvisiblesComp()
    {
        //LABELS
        userl.setVisible(false);
        nombrel.setVisible(false);
        namel.setVisible(false);
        fechainil.setVisible(false);
        fechafinl.setVisible(false);
        edadinil.setVisible(false);
        edadfinl.setVisible(false);
        idl.setVisible(false);
        lastnamel.setVisible(false);
        lastname2l.setVisible(false);
        gradol.setVisible(false);
        
        //BOTONES
        buscar.setVisible(false);
        buscar2.setVisible(false);
        
        //PANELES Y COMBOBOX
        userf.setVisible(false);
        nombref.setVisible(false);
        namef.setVisible(false);
        fechainif.setVisible(false);
        fechafinf.setVisible(false);
        edadinif.setVisible(false);
        edadfinf.setVisible(false);
        idf.setVisible(false);
        lastnamef.setVisible(false);
        lastname2f.setVisible(false);
        gradof.setVisible(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        p11 = new javax.swing.JPanel();
        nombrel = new javax.swing.JLabel();
        fechainif = new com.toedter.calendar.JDateChooser();
        fechafinf = new com.toedter.calendar.JDateChooser();
        fechainil = new javax.swing.JLabel();
        fechafinl = new javax.swing.JLabel();
        nombref = new javax.swing.JComboBox<>();
        edadfinf = new com.toedter.calendar.JDateChooser();
        edadinil = new javax.swing.JLabel();
        edadfinl = new javax.swing.JLabel();
        edadinif = new com.toedter.calendar.JDateChooser();
        gradol = new javax.swing.JLabel();
        gradof = new javax.swing.JComboBox<>();
        namel = new javax.swing.JLabel();
        namef = new javax.swing.JTextField();
        lastnamel = new javax.swing.JLabel();
        lastnamef = new javax.swing.JTextField();
        lastname2l = new javax.swing.JLabel();
        lastname2f = new javax.swing.JTextField();
        idl = new javax.swing.JLabel();
        idf = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        userl = new javax.swing.JLabel();
        userf = new javax.swing.JTextField();
        buscar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 600));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setPreferredSize(new java.awt.Dimension(650, 70));

        nombrel.setText("Nombre Empresa");

        fechainif.setDateFormatString("DD/MM/YYYY");
        fechainif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fechafinf.setDateFormatString("DD/MM/YYYY");
        fechafinf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        fechainil.setText("De: ");

        fechafinl.setText("hasta:");

        nombref.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edadfinf.setDateFormatString("DD/MM/YYYY");
        edadfinf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        edadinil.setText("Edad de");

        edadfinl.setText("hasta:");

        edadinif.setDateFormatString("DD/MM/YYYY");
        edadinif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        gradol.setText("G. Academico");

        gradof.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        namel.setText("Nombre");

        lastnamel.setText("Primer Apellido ");

        lastname2l.setText("Segundo Apellido");

        idl.setText("Cedula");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        userl.setText("Usuario");

        userf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfActionPerformed(evt);
            }
        });

        buscar2.setText("Buscar");

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addComponent(fechainil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(fechainif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(namel)
                        .addGap(13, 13, 13)
                        .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lastnamel)
                        .addGap(17, 17, 17)
                        .addComponent(lastnamef, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addComponent(fechafinl)
                        .addGap(19, 19, 19)
                        .addComponent(fechafinf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(idl)
                        .addGap(7, 7, 7)
                        .addComponent(idf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lastname2l)
                        .addGap(8, 8, 8)
                        .addComponent(lastname2f, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(nombrel)
                                .addGap(9, 9, 9)
                                .addComponent(nombref, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(gradol)
                                .addGap(11, 11, 11)
                                .addComponent(gradof, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscar2))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(edadinil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(edadinif, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(edadfinl)
                                .addGap(9, 9, 9)
                                .addComponent(edadfinf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p11Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(userl)
                                .addGap(14, 14, 14)
                                .addComponent(userf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechainil)
                    .addComponent(fechainif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namel)
                    .addComponent(namef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lastnamel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lastnamef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechafinl)
                    .addComponent(fechafinf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idl)
                    .addComponent(idf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname2l)
                    .addComponent(lastname2f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrel)
                    .addComponent(nombref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edadinil)
                            .addComponent(edadinif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadfinl)
                            .addComponent(edadfinf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gradol)
                            .addComponent(gradof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar)
                            .addComponent(buscar2)))))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );

        jMenu1.setText("Consultas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Usuarios sin modificar Clave");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Empresas Asociadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Puesto por empresa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones");

        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Editar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Eliminar");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estadísticas");

        jMenuItem7.setText("Solicitantes por edad");
        jMenu3.add(jMenuItem7);

        jMenuItem9.setText("Solicitantes por Canton");
        jMenu3.add(jMenuItem9);

        jMenuItem8.setText("Solicitantes por distrito");
        jMenu3.add(jMenuItem8);

        jMenuItem10.setText("Solicitantes por provincia");
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Top N de empresas con mayor solicitud");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Top N de puestos con mayor solicitud");
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p11, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        p11.setVisible(true);
        namel.setVisible(true);
        namef.setVisible(true);
        lastnamel.setVisible(true);
        lastname2l.setVisible(true);
        lastnamef.setVisible(true);
        lastname2f.setVisible(true);
        idl.setVisible(true);
        idf.setVisible(true);
        userl.setVisible(true);
        userf.setVisible(true);
        fechainil.setVisible(true);
        fechainif.setVisible(true);
        fechafinl.setVisible(true);
        fechafinf.setVisible(true);
        buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        MyConnection mc=null;
        CallableStatement cs;
        try {
            cs= mc.getConnection().prepareCall("call empresa_qpuestos()");
            ResultSet rs = cs.executeQuery();
            while (rs.next()) {
            System.out.println("Nombre = " + rs.getString(1) + ", Total= " + rs.getInt(2));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        p11.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        //USUARIOS SIN CAMBIAR CLAVE
        t.usuariosSinCambio(tabla);
        String nombre = nombref.getSelectedItem().toString();
        String edadde = edadfinf.getDate().toString();
        String edadhasta = edadinif.getDate().toString();
        String publide = fechainif.getDate().toString();
        String publihasta = fechafinf.getDate().toString();
        DefaultTableModel modelo = new DefaultTableModel();
        this.tabla.setModel(modelo);
        
    }//GEN-LAST:event_buscarActionPerformed

    private void userfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton buscar2;
    private com.toedter.calendar.JDateChooser edadfinf;
    private javax.swing.JLabel edadfinl;
    private com.toedter.calendar.JDateChooser edadinif;
    private javax.swing.JLabel edadinil;
    private com.toedter.calendar.JDateChooser fechafinf;
    private javax.swing.JLabel fechafinl;
    private com.toedter.calendar.JDateChooser fechainif;
    private javax.swing.JLabel fechainil;
    private javax.swing.JComboBox<String> gradof;
    private javax.swing.JLabel gradol;
    private javax.swing.JTextField idf;
    private javax.swing.JLabel idl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastname2f;
    private javax.swing.JLabel lastname2l;
    private javax.swing.JTextField lastnamef;
    private javax.swing.JLabel lastnamel;
    private javax.swing.JTextField namef;
    private javax.swing.JLabel namel;
    private javax.swing.JComboBox<String> nombref;
    private javax.swing.JLabel nombrel;
    private javax.swing.JPanel p11;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField userf;
    private javax.swing.JLabel userl;
    // End of variables declaration//GEN-END:variables
}
