/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chaodesempleo;

import Utilidades.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Mariela
 */
public class FormularioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormularioAdmin
     */
    Tabla t = new Tabla();
    databaseManager conectar;
    DefaultTableModel modelo = new DefaultTableModel();
<<<<<<< HEAD
        public String pnombre = "";
        public String papellido1 = "";
        public String papellido2 = "";
        public String pcedula = "";
        public String puser = "";
        
        public String pEdad1 = "1960/01/01";
        public String pEdad2 = "2000/01/01";
        public String pfecha1 = "2018/10/01";
        public String pfecha2 = "2018/12/31";
        
        public String pEmpresa = "";
        public String pGAcademico = "";
        public String pPuesto = "";
        
        
    public FormularioAdmin() {
        initComponents();
        p11.setVisible(false);
        InvisiblesComp();
       
       
    }
     public void InvisiblesComp()
=======
    
    public void InvisiblesComp()
>>>>>>> e45775ef7bc9e4ae9deafe53f9ab28052599a654
    {
        //LABELS
        userl.setVisible(false);
        lblEmpresa.setVisible(false);
        namel.setVisible(false);
        fechainil.setVisible(false);
        fechafinl.setVisible(false);
        edadinil.setVisible(false);
        edadfinl.setVisible(false);
        idl.setVisible(false);
        lastnamel.setVisible(false);
        lastname2l.setVisible(false);
        lblgAcademico.setVisible(false);
        
        //BOTONES
        btnbuscarC2.setVisible(false);
        btnBuscarC3.setVisible(false);
        
        //PANELES Y COMBOBOX
        txtUser.setVisible(false);
        cbEmpresa.setVisible(false);
        txtNombre.setVisible(false);
        dcFechaI.setVisible(false);
        dcFechaF.setVisible(false);
        dcEdadI.setVisible(false);
        dcEdadF.setVisible(false);
        txtCedula.setVisible(false);
        txtApellido1.setVisible(false);
        txtApellido2.setVisible(false);
        cbGradoA.setVisible(false);  
        cbPuesto.setVisible(false);
        lblPuesto.setVisible(false);
    }
    public void LimpiarcbEmpresa(){
        int ItemCount  = cbEmpresa.getItemCount();
        for(int i=0; i<ItemCount; i++){
            cbEmpresa.remove(0);
        }
    } 
     public void llenarCBEmpresa(){
        LimpiarcbEmpresa();
        try{           
            ResultSet r;
            r = ChaoDesempleo.dbManager.mostrarEmpresa();
            cbEmpresa.addItem("Seleccione:");
            while (r.next()){
                cbEmpresa.addItem(r.getString(1));                
            }        
        }catch (Exception e) {e.printStackTrace();}
    }
    
    public void LimpiarcbGradoA(){
        int ItemCount  = cbGradoA.getItemCount();
        for(int i=0; i<ItemCount; i++){
            cbGradoA.remove(0);
        }
    } 
     public void llenarCBGradoA(){
        LimpiarcbGradoA();
        try{           
            ResultSet r;
            r = ChaoDesempleo.dbManager.mostrarGradoA();
            cbGradoA.addItem("Seleccione:");
            while (r.next()){
                cbGradoA.addItem(r.getString(1));                
            }        
        }catch (Exception e) {e.printStackTrace();}
    }

<<<<<<< HEAD
     public void LimpiarcbPuesto(){
        int ItemCount  = cbPuesto.getItemCount();
        for(int i=0; i<ItemCount; i++){
            cbPuesto.remove(0);
        }
    } 
     public void llenarCBPuesto(){
        LimpiarcbPuesto();
        try{           
            ResultSet r;
            r = ChaoDesempleo.dbManager.mostrarPuesto();
            cbPuesto.addItem("Seleccione:");
            while (r.next()){
                cbPuesto.addItem(r.getString(1));                
            }        
        }catch (Exception e) {e.printStackTrace();}
    }
     
=======
    public FormularioAdmin() {
        initComponents();
        p11.setVisible(false);
        InvisiblesComp();
    }
     

>>>>>>> e45775ef7bc9e4ae9deafe53f9ab28052599a654
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        p11 = new javax.swing.JPanel();
        dcFechaI = new com.toedter.calendar.JDateChooser();
        dcFechaF = new com.toedter.calendar.JDateChooser();
        fechainil = new javax.swing.JLabel();
        fechafinl = new javax.swing.JLabel();
        dcEdadF = new com.toedter.calendar.JDateChooser();
        edadinil = new javax.swing.JLabel();
        edadfinl = new javax.swing.JLabel();
        dcEdadI = new com.toedter.calendar.JDateChooser();
        namel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lastnamel = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        lastname2l = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        idl = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnbuscarC2 = new javax.swing.JButton();
        userl = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnBuscarC3 = new javax.swing.JButton();
        pTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        lblgAcademico = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox<>();
        cbGradoA = new javax.swing.JComboBox<>();
        lblPuesto = new javax.swing.JLabel();
        cbPuesto = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Administrador");
        setPreferredSize(new java.awt.Dimension(850, 550));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setPreferredSize(new java.awt.Dimension(650, 70));

        dcFechaI.setDateFormatString("DD/MM/YYYY");
        dcFechaI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        dcFechaF.setDateFormatString("DD/MM/YYYY");
        dcFechaF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        fechainil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechainil.setForeground(new java.awt.Color(153, 153, 153));
        fechainil.setText("De: ");

        fechafinl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechafinl.setForeground(new java.awt.Color(153, 153, 153));
        fechafinl.setText("hasta:");

        dcEdadF.setDateFormatString("DD/MM/YYYY");
        dcEdadF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        edadinil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edadinil.setForeground(new java.awt.Color(153, 153, 153));
        edadinil.setText("Edad de");

        edadfinl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edadfinl.setForeground(new java.awt.Color(153, 153, 153));
        edadfinl.setText("Hasta:");

        dcEdadI.setDateFormatString("DD/MM/YYYY");
        dcEdadI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        namel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namel.setForeground(new java.awt.Color(153, 153, 153));
        namel.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lastnamel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastnamel.setForeground(new java.awt.Color(153, 153, 153));
        lastnamel.setText("Apellido 1");

        txtApellido1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lastname2l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastname2l.setForeground(new java.awt.Color(153, 153, 153));
        lastname2l.setText("Apellido 2");

        txtApellido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        idl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idl.setForeground(new java.awt.Color(153, 153, 153));
        idl.setText("Cedula");

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnbuscarC2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbuscarC2.setText("Buscar");
        btnbuscarC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarC2ActionPerformed(evt);
            }
        });

        userl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userl.setForeground(new java.awt.Color(153, 153, 153));
        userl.setText("Usuario");

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnBuscarC3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarC3.setText("Buscar");
        btnBuscarC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarC3ActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("jLabel1");

        javax.swing.GroupLayout pTituloLayout = new javax.swing.GroupLayout(pTitulo);
        pTitulo.setLayout(pTituloLayout);
        pTituloLayout.setHorizontalGroup(
            pTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pTituloLayout.setVerticalGroup(
            pTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        lblEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmpresa.setForeground(new java.awt.Color(153, 153, 153));
        lblEmpresa.setText("Empresa");

        lblgAcademico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblgAcademico.setForeground(new java.awt.Color(153, 153, 153));
        lblgAcademico.setText("Grado Academico");

        cbEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbGradoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(153, 153, 153));
        lblPuesto.setText("Puesto");

        cbPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout p11Layout = new javax.swing.GroupLayout(p11);
        p11.setLayout(p11Layout);
        p11Layout.setHorizontalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(p11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addComponent(edadfinl)
                        .addGap(31, 31, 31)
                        .addComponent(dcEdadF, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p11Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(edadinil))
                                    .addComponent(fechainil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dcFechaI, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(dcFechaF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcEdadI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p11Layout.createSequentialGroup()
                                .addComponent(fechafinl)
                                .addGap(73, 73, 73)))
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p11Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblgAcademico)
                                    .addComponent(lblPuesto)
                                    .addComponent(btnbuscarC2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(lblEmpresa)
                                .addGap(65, 65, 65)))
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p11Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(btnBuscarC3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                                    .addGroup(p11Layout.createSequentialGroup()
                                        .addComponent(cbPuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p11Layout.createSequentialGroup()
                                        .addComponent(lastnamel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(p11Layout.createSequentialGroup()
                                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastname2l)
                                            .addComponent(userl, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbEmpresa, 0, 200, Short.MAX_VALUE)
                                    .addComponent(cbGradoA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCedula)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p11Layout.setVerticalGroup(
            p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p11Layout.createSequentialGroup()
                .addComponent(pTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(fechainil))
                            .addComponent(dcFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(dcFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(fechafinl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edadinil)
                            .addComponent(dcEdadI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcEdadF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadfinl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(p11Layout.createSequentialGroup()
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpresa)
                                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblgAcademico)
                                    .addComponent(cbGradoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namel)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idl)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p11Layout.createSequentialGroup()
                                .addComponent(cbPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnbuscarC2)
                                    .addComponent(btnBuscarC3)))
                            .addGroup(p11Layout.createSequentialGroup()
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastnamel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastname2l))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(p11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 9, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Consultas");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Empresas Asociadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Puesto por empresa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Usuarios sin modificar Clave");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operaciones");

        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Editar");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Eliminar");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estadísticas");

        jMenuItem7.setText("Solicitantes por edad");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem9.setText("Solicitantes por Canton");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem8.setText("Solicitantes por distrito");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem10.setText("Solicitantes por provincia");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Top N de empresas con mayor solicitud");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Top N de puestos con mayor solicitud");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        p11.setVisible(true);
        namel.setVisible(true);
        txtNombre.setVisible(true);
        lastnamel.setVisible(true);
        lastname2l.setVisible(true);
        txtApellido1.setVisible(true);
        txtApellido2.setVisible(true);
        idl.setVisible(true);
        txtCedula.setVisible(true);
        userl.setVisible(true);
        txtUser.setVisible(true);
        fechainil.setVisible(true);
        dcFechaI.setVisible(true);
        fechafinl.setVisible(true);
        dcFechaF.setVisible(true);
        btnbuscarC2.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        InvisiblesComp();
        modelo = new DefaultTableModel();
        lblTitulo.setText("EMPRESAS ASOCIADAS");
        lblTitulo.setVisible(true);
        pTitulo.setVisible(true);
        p11.setVisible(true);
        try {
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.empresa_QPuestos();
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch  (Exception e) {e.printStackTrace();}
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here
        modelo = new DefaultTableModel();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        modelo = new DefaultTableModel();
                
        lblTitulo.setText("PUESTOS DE TRABAJO");
        lblTitulo.setVisible(true);
        pTitulo.setVisible(true);
        p11.setVisible(true);        
       
        fechainil.setVisible(true);
        fechafinl.setVisible(true);
        edadinil.setVisible(true);
        edadfinl.setVisible(true);       
        dcFechaI.setVisible(true);
        dcFechaF.setVisible(true);
        dcEdadI.setVisible(true);
        dcEdadF.setVisible(true);
        
        lblEmpresa.setVisible(true);
        lblgAcademico.setVisible(true);
        lblPuesto.setVisible(true);
        cbGradoA.setVisible(true);  
        cbPuesto.setVisible(true); 
        cbEmpresa.setVisible(true);
        
        btnbuscarC2.setVisible(true);
        
        llenarCBEmpresa(); llenarCBGradoA(); llenarCBPuesto();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnbuscarC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarC2ActionPerformed
<<<<<<< HEAD
        //Consulta 2 Puesto de trabajo
        pEmpresa = cbEmpresa.getSelectedItem().toString();
        pGAcademico = cbGradoA.getSelectedItem().toString();
        pPuesto = cbPuesto.getSelectedItem().toString();       
        
        pEdad1 = dcEdadI.getDate().toString();
        pEdad2 = dcEdadF.getDate().toString();
        pfecha1 = dcFechaI.getDate().toString();
        pfecha2 = dcFechaF.getDate().toString();
               
        try {
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.Puestos(pEmpresa, pPuesto, pEdad1, pEdad2, pGAcademico, pfecha1, pfecha2);
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch  (Exception e) {e.printStackTrace();}
=======
        //USUARIOS SIN CAMBIAR CLAVE
        t.usuariosSinCambio(tabla);
        String nombre = nombref.getSelectedItem().toString();
        String edadde = edadfinf.getDate().toString();
        String edadhasta = edadinif.getDate().toString();
        String publide = fechainif.getDate().toString();
        String publihasta = fechafinf.getDate().toString();
        modelo = new DefaultTableModel(0,0);
        this.tabla.setModel(modelo);
>>>>>>> e45775ef7bc9e4ae9deafe53f9ab28052599a654
        
    }//GEN-LAST:event_btnbuscarC2ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        InvisiblesComp();
        lblTitulo.setText("ESTADISTICAS: Solicitantes por edad");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.SolicitantesxEdad();
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }     
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        lblTitulo.setText("ESTADISTICAS: Solicitantes por distrito");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.SolicitantesxDistrito();
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        lblTitulo.setText("ESTADISTICAS: Solicitantes por canton");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.SolicitantesxCanton();
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        lblTitulo.setText("ESTADISTICAS: Solicitantes por provincia");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.SolicitantesxProvincia();
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        lblTitulo.setText("ESTADISTICAS: Top N de empresas con mayor solicitud");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.empresaxjobs(3);
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        lblTitulo.setText("ESTADISTICAS: Top N de puestos con mayor solicitud");
        lblTitulo.setVisible(true);
        try {
            modelo = new DefaultTableModel(0,0);
            this.tabla.setModel(modelo);
            ResultSet r;
            r = ChaoDesempleo.dbManager.jobxsolicitantes(3);
            ResultSetMetaData rsMd = r.getMetaData();
            int cntddColumnas = rsMd.getColumnCount();
            for (int i=1; i<=cntddColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (r.next()){
                Object[] fila = new Object[cntddColumnas];
                for(int i=0; i<cntddColumnas; i++){
                    fila[i]=r.getObject(i+1);
                }               
                modelo.addRow(fila);
            }        
        } catch (SQLException ex) {
            Logger.getLogger(FormularioAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void btnBuscarC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarC3ActionPerformed
        
    }//GEN-LAST:event_btnBuscarC3ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarC3;
    private javax.swing.JButton btnbuscarC2;
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JComboBox<String> cbGradoA;
    private javax.swing.JComboBox<String> cbPuesto;
    private com.toedter.calendar.JDateChooser dcEdadF;
    private com.toedter.calendar.JDateChooser dcEdadI;
    private com.toedter.calendar.JDateChooser dcFechaF;
    private com.toedter.calendar.JDateChooser dcFechaI;
    private javax.swing.JLabel edadfinl;
    private javax.swing.JLabel edadinil;
    private javax.swing.JLabel fechafinl;
    private javax.swing.JLabel fechainil;
    private javax.swing.JLabel idl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastname2l;
    private javax.swing.JLabel lastnamel;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblgAcademico;
    private javax.swing.JLabel namel;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel pTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel userl;
    // End of variables declaration//GEN-END:variables
}
