Delimiter $$
#ADMIN CONSULTA 2: ElISTADO DE PUESTOS
CREATE PROCEDURE `LISTADO_PUESTOS`(IN pEMPRESA VARCHAR(100), IN pPUESTO VARCHAR(60), IN pEDAD1 DATE, IN pEDAD2 DATE,
	IN pGRADOAC VARCHAR(100), IN pFECHAPUB1 DATE, IN pFECHAPUB2 DATE)
MODIFIES SQL DATA
BEGIN
	SELECT CONCAT(P.name,' ',P.lastname1,' ',P.lastname2) AS EMPRESA, JP.NAME AS PUESTO, J.DESCRIPTION AS DESCRIPCION,
	J.BIRTHDATE AS FECHANAC, J.PUBDATE AS PUBLICADO, J.DUEDATE AS CADUCA, J.VACANCIES AS VACANTES, AD.NAME AS ACADEMICO
    
	FROM JOB J INNER JOIN job_position JP
	ON J.ID_JOBPOS=JP.ID_JOB_POSITION AND JP.NAME LIKE CONCAT('%',pPUESTO,'%') AND j.id_state=1 and (J.PUBDATE BETWEEN pFECHAPUB1 AND pFECHAPUB2) AND (J.BIRTHDATE BETWEEN pEDAD1 AND pEDAD2)
		INNER JOIN academic_degree AD ON AD.ID_ACADEMIC_DEGREE=J.ID_ADEGREE AND AD.NAME LIKE CONCAT('%',pGRADOAC,'%')
			INNER JOIN JOBXPERSON JXP ON J.ID_JOB=JXP.ID_JOB
				INNER JOIN PERSON P ON JXP.ID_PERSON=P.ID_PERSON AND CONCAT(P.name,' ',P.lastname1,' ',P.lastname2) LIKE CONCAT('%',pEMPRESA,'%')
	
    ORDER BY PUESTO, EMPRESA;
#NOTA: LOS PARAMETRO QUE INVOLUCARAN FECHAS DEBEN TENER ALGÚN VALOR
END$$

delimiter ;