Delimiter $$

CREATE PROCEDURE `getJob`()
MODIFIES SQL DATA
BEGIN
  SELECT ID_JOB, BIRTHDATE, DESCRIPTIONm PUBDATE, DUEDATE, VACANCIES, ID_STATE, ID_JOBPOS, ID_CAREER, ID_ADEGREE FROM job;
END$$

delimiter ;