Delimiter $$

CREATE PROCEDURE `getJob`(IN PID_JOB INT)
MODIFIES SQL DATA
BEGIN
  SELECT ID_JOB, BIRTHDATE, DESCRIPTION PUBDATE, DUEDATE, VACANCIES, ID_STATE, ID_JOBPOS, ID_CAREER, ID_ADEGREE FROM job
    where id_JOB = isnull (pid_JOB,id_JOB);

END$$

delimiter ;
