DELIMITER $$
CREATE TRIGGER buser_before_update BEFORE UPDATE ON buser
FOR EACH ROW BEGIN
    SET new.DATE_LAST_MODIFICATION = NOW(),
        new.USER_LAST_MODIFICATION = system_user();
	END; $$
    
DELIMITER ;